### ISSUE TITLE
Get it working :)

### ISSUE THREAD

**Issue by rohancyriac029** [acmpesuecc/signup#1]
Find all necessary packages to be imported such that the flask is running and all functions are working.
You can test this by signing up after the code is run and you can check if the details are entered being collected in the database file by running check.py

**Comment by Git-Cat-21** [comment]
Can i be assigned to this

**Comment by rohancyriac029** [comment]
!assign @Git-Cat-21 30

**Comment by rohancyriac029** [comment]
!deassign

**Comment by Git-Cat-21** [comment]
i have fixed the issue why has it been deassigned i am about to make a PR

**Comment by rohancyriac029** [comment]
!assign @Git-Cat-21  30

**Comment by rohancyriac029** [comment]
!bounty 10
