### ISSUE TITLE
Link a new page be it night or day

### ISSUE THREAD

**Issue by rohancyriac029** [acmpesuecc/signup#3]
If you login with an account that had chosen doctor as profession,it takes you to a doctor page which contains an appointments tab.
I have already liked a css file and html file for it in static and templates folders. Link those to the to the appointments option by seeing previous examples for signup and login pages. Also the doctor page has a dummy light and dark mode toggler, remove that and replace it with one that works.

**Comment by Lalith2907** [comment]
can you assign me this

**Comment by rohancyriac029** [comment]
!assign @Lalith2907

**Comment by rohancyriac029** [comment]
!assign @Lalith2907 60

**Comment by rohancyriac029** [comment]
@Lalith2907 this has assigned you 60 minutes you can request for more by pinging

**Comment by Lalith2907** [comment]
ok alright thanks

**Comment by Greninja44** [comment]
can i get assigned

**Comment by Lalith2907** [comment]
@rohancyriac029 going for dinner rn

**Comment by Git-Cat-21** [comment]
can i get assigned to this

**Comment by rohancyriac029** [comment]
@Lalith2907 you want me to extend time for this?

**Comment by rohancyriac029** [comment]
!extend 30

**Comment by rohancyriac029** [comment]
@Lalith2907 let me know if youre still working on it

**Comment by Lalith2907** [comment]
umm no actually u can unassign me

**Comment by rohancyriac029** [comment]
You are automatically unassigned as time ran out

**Comment by rohancyriac029** [comment]
!deassign

**Comment by asmitdesai** [comment]
can i get this

**Comment by rohancyriac029** [comment]
@asmitdesai would you still liked to be assigned to this

**Comment by asmitdesai** [comment]
yes

**Comment by rohancyriac029** [comment]
!assign @asmitdesai  60

**Comment by rohancyriac029** [comment]
@asmitdesai you have already been assigned to another repo

**Comment by asmitdesai** [comment]
i dont have anything showing up on git

**Comment by Nightwing000** [comment]
can i get this assigned

**Comment by rohancyriac029** [comment]
Asmit i will try to assign it to you once more

**Comment by rohancyriac029** [comment]
!assign @asmitdesai 60

**Comment by rohancyriac029** [comment]
@asmitdesai you have been assigned to it for 60 mins good luck you can ping me for extensions

**Comment by Git-Cat-21** [comment]
can i be assigned to it

**Comment by rohancyriac029** [comment]
> can i be assigned to it

there are already people working on it

**Comment by sherlockhome12** [comment]
hey can i get assigned to this??

**Comment by rohancyriac029** [comment]
!deassign

**Comment by rohancyriac029** [comment]
!assign @asmitdesai 30

**Comment by asmitdesai** [comment]
what is the error

**Comment by rohancyriac029** [comment]
@asmitdesai can you tell me the sem hall you are in

**Comment by asmitdesai** [comment]
can you desassign me

**Comment by rohancyriac029** [comment]
ok

**Comment by rohancyriac029** [comment]
!deassign

**Comment by sherlockhome12** [comment]
hey can i get assigned??

**Comment by rohancyriac029** [comment]
!assign @sherlockhome12 60

**Comment by rohancyriac029** [comment]
@sherlockhome12 you have already been assigned to another repo

**Comment by sherlockhome12** [comment]
does it tell which repo?

**Comment by H-Mudliar** [comment]
Can you please assign this to me

**Comment by rohancyriac029** [comment]
!assign @H-Mudliar 60

**Comment by rohancyriac029** [comment]
> does it tell which repo?

sorry i dont have access to that

**Comment by Git-Cat-21** [comment]
can i be assigned to it

**Comment by rohancyriac029** [comment]
!deassign

**Comment by rohancyriac029** [comment]
!assign @Git-Cat-21 60

**Comment by rohancyriac029** [comment]
!assign @Git-Cat-21 60

**Comment by rohancyriac029** [comment]
you are already assigned in another repo

**Comment by Udaya-G** [comment]
can i please get assigned to this

**Comment by rohancyriac029** [comment]
!assign @Udaya-G 60

**Comment by rohancyriac029** [comment]
youve been assigned 60 mins 
note that the current toggle is just a theme and not an actual button you need to replace that as well and then make it functional

**Comment by Udaya-G** [comment]
> !assign @Udaya-G 60

sorry not working on it  because of the events

**Comment by rohancyriac029** [comment]
> > !assign @Udaya-G 60
> 
> sorry not working on it because of the events

do you want to be deassigned or an extension?

**Comment by rohancyriac029** [comment]
!deassign

**Comment by Nightwing000** [comment]
can i be assigned this ?

**Comment by rohancyriac029** [comment]
!assign @Nightwing000 60

**Comment by rohancyriac029** [comment]
@Nightwing000 the toggle key right now is just a theme and is not a functioning button you need to convert that to a dark and light mode theme changer by making it a button first, doesnt matter how it looks

**Comment by Nightwing000** [comment]
thanks

**Comment by 1anagha7** [comment]
please assign me this

**Comment by Nightwing000** [comment]
so can i not use the already provided theme and just switch the color of the text and background?

**Comment by sherlockhome12** [comment]
hey can i be assigned on this? i m not working on any other repo

**Comment by rohancyriac029** [comment]
@Nightwing000 do you require any extension?

**Comment by rohancyriac029** [comment]
> so can i not use the already provided theme and just switch the color of the text and background?

that theme is not interactable as it is a span element you will get to know this if you do inspect element on the website that is if you run the code and try it out first

**Comment by Nightwing000** [comment]
I know but I thought we had to use it as a template for how the dark mode should look
I've made the button and stuff but I'm getting a strict MIME error 
can you extend for 30 minutes I"ll try to get past it

**Comment by rohancyriac029** [comment]
yea sure

**Comment by rohancyriac029** [comment]
!deassign

**Comment by rohancyriac029** [comment]
!assign @Nightwing000 30

**Comment by rohancyriac029** [comment]
!assign @Nightwing000 40

**Comment by rohancyriac029** [comment]
@Nightwing000 ive added 40 mins more

**Comment by Nightwing000** [comment]
thanks

**Comment by Nightwing000** [comment]
can you make a branch for me to push into?

**Comment by rohancyriac029** [comment]
just make pr to main

**Comment by rohancyriac029** [comment]
@Nightwing000 ill check and let you know in a bit

**Comment by Nightwing000** [comment]
yeah thanks

**Comment by rohancyriac029** [comment]
@Nightwing000 can you just check the comment on your pr

**Comment by rohancyriac029** [comment]
!deassign
