### ISSUE TITLE
Wait your turn

### ISSUE THREAD

**Issue by rohancyriac029** [acmpesuecc/signup#4]
Let's proceed by logging into an account where 'Doctor' is selected as the profession, since other roles don't have a landing page yet—this way, you can avoid working on the HTML and CSS. You'll find a logout button in the bottom left corner, which is already set up for you. Ensure that once a user is authenticated and logged in with their credentials, access to the landing page is restricted to only that session, preventing any other users from accessing it concurrently. Also, ensure the logout button redirects back to the sign-in page.

**Comment by Anyaaa-2** [comment]
can i get assigned

**Comment by rohancyriac029** [comment]
!assign @Anyaaa-2 60

**Comment by rohancyriac029** [comment]
@Anyaaa-2 you are already assigned to a repo

**Comment by Git-Cat-21** [comment]
can i be assigned to this

**Comment by rohancyriac029** [comment]
!assign @Git-Cat-21 60

**Comment by rohancyriac029** [comment]
@Git-Cat-21 you have been assigned  60 minutes

**Comment by Hemaksh-b** [comment]
can i be assigned this next

**Comment by Anyaaa-2** [comment]
can u extend the time , im going to eat

**Comment by rohancyriac029** [comment]
i will extend after the time runs out

**Comment by rohancyriac029** [comment]
@Git-Cat-21 let me check your pr

**Comment by rohancyriac029** [comment]
@Anyaaa-2 you are not the person the problem has been assigned to

**Comment by rohancyriac029** [comment]
@Git-Cat-21 partial points cannot be awarded for the redirecting as it is not the crux of the issue

**Comment by Anyaaa-2** [comment]
can i be assigned

**Comment by rohancyriac029** [comment]
!deassign

**Comment by rohancyriac029** [comment]
@Anyaaa-2  give me a few seconds the bot is down for a few minutes i can assign you after if you still want it

**Comment by Anyaaa-2** [comment]
ya sure

**Comment by rohancyriac029** [comment]
!deassign

**Comment by rohancyriac029** [comment]
@Anyaaa-2 shall I assign it to you

**Comment by Anyaaa-2** [comment]
yes

**Comment by rohancyriac029** [comment]
!assign @Anyaaa-2 60

**Comment by rohancyriac029** [comment]
!assign @Anyaaa-2 60

**Comment by rohancyriac029** [comment]
@Anyaaa-2 youve been assigned 60 mins you can dm for extensions

**Comment by Tulika7032** [comment]
hey can i get assigned this repo??

**Comment by rohancyriac029** [comment]
!assign @Tulika7032 60

**Comment by rohancyriac029** [comment]
@Tulika7032 have you already been assigned to another repo??

**Comment by DhanushSS** [comment]
pls assign me

**Comment by shreyasoni26** [comment]
can i be assigned this

**Comment by rohancyriac029** [comment]
!assign @DhanushSS 60

**Comment by rohancyriac029** [comment]
@DhanushSS you may have already been assigned to another repo

**Comment by rohancyriac029** [comment]
@shreyasoni26  would you like to be assigned?

**Comment by diyah1234** [comment]
can I be assigned to this?

**Comment by shreyasoni26** [comment]
yes please

**Comment by DhanushSS** [comment]
> @DhanushSS you may have already been assigned to another repo

can i check where am i assigned ?

**Comment by rohancyriac029** [comment]
!assign @shreyasoni26 60

**Comment by rohancyriac029** [comment]
!assign @shreyasoni26 60

**Comment by DhanushSS** [comment]
@rohancyriac029 can i see where am i already assigned ?

**Comment by rohancyriac029** [comment]
I am sorry guys there seems to be some tech issue with the bot well fix it and get back to you and @DhanushSS if it was a issue on this side and u have not been assigned anything i will check that and assign it to you since you were here first

**Comment by DhanushSS** [comment]
I got assigned in other place .

**Comment by rohancyriac029** [comment]
> I got assigned in other place .

yea i figured

**Comment by rohancyriac029** [comment]
> can I be assigned to this?

would you like to be assigned if you have not been assigned elsewhere

**Comment by sakshipai213** [comment]
please assign me

**Comment by rohancyriac029** [comment]
!deassign

**Comment by rohancyriac029** [comment]
!assign @sakshipai213 60

**Comment by rohancyriac029** [comment]
@sakshipai213  you have been assigned for 60 mins u can ping me for extensions

**Comment by rohancyriac029** [comment]
!deassign

**Comment by noobieeeeeee** [comment]
Can I be assigned this? @rohancyriac029

**Comment by shreyasoni26** [comment]
can i please be assigned

**Comment by rohancyriac029** [comment]
!assign @noobieeeeeee 60

**Comment by rohancyriac029** [comment]
@noobieeeeeee you were already assigned to another repo

**Comment by noobieeeeeee** [comment]
i was

**Comment by rohancyriac029** [comment]
!asssign @shreyasoni26 60

**Comment by rohancyriac029** [comment]
@shreyasoni26 you are also assigned to another repo

**Comment by noobieeeeeee** [comment]
@rohancyriac029 im not assigned to anything else, please recheck

**Comment by shreyasoni26** [comment]
> !asssign @shreyasoni26 60

i think there's a spelling mistake here
in "assign"

**Comment by rohancyriac029** [comment]
> > !asssign @shreyasoni26 60
> 
> i think there's a spelling mistake here in "assign"

i am really sorry

**Comment by rohancyriac029** [comment]
!assign @shreyasoni26 60

**Comment by shreyasoni26** [comment]
thanks

**Comment by rohancyriac029** [comment]
@shreyasoni26 do you want an extension or would you like me to deassign you?

**Comment by rohancyriac029** [comment]
!deassign

**Comment by rohancyriac029** [comment]
@shreyasoni26 if you want to work on it further ping me

**Comment by sherlockhome12** [comment]
hey can i be assigned this??

**Comment by sherlockhome12** [comment]
@rohancyriac029

**Comment by rohancyriac029** [comment]
@sherlockhome12 i am sorry for the delay

**Comment by rohancyriac029** [comment]
!assign @sherlockhome12 60

**Comment by rohancyriac029** [comment]
youve been already assigned

**Comment by sherlockhome12** [comment]
there is a confusion

**Comment by sherlockhome12** [comment]
i was working on one repo and that repo got deassigned but somehow its displaying i m working under a repo

**Comment by sherlockhome12** [comment]
can i still continue working?

**Comment by rohancyriac029** [comment]
let me check if I still cant assign you

**Comment by rohancyriac029** [comment]
!assign @sherlockhome12 60

**Comment by rohancyriac029** [comment]
Did you withdraw or were you deassigned by the maintainer?

**Comment by KaparthyReddy** [comment]
kindly assign this.

**Comment by rohancyriac029** [comment]
!assign @KaparthyReddy 60

**Comment by devanshishukla17** [comment]
can i please get this assigned

**Comment by rohancyriac029** [comment]
!deassign

**Comment by rohancyriac029** [comment]
!assign @devanshishukla17 60

**Comment by rohancyriac029** [comment]
@devanshishukla17 uve already been assigned something else

**Comment by devanshishukla17** [comment]
no

**Comment by rohancyriac029** [comment]
!assign @devanshishukla17 60
